### ISSUE TITLE
Workflow Enhancement - Wrapper Mappings

### ISSUE THREAD

**Issue by its-a-feature** [som3canadian/Mythic_NimSyscallPacker_Wrapper#4]
Due to popular request, there's an enhancement you can make in your wrapper to make it a bit smoother to use with additional agents. 

Make sure you're on the latest Mythic, but this section:
>Since this is not an official Mythic agent, you need to modify the agent config to support the new wrapper. You can do this by modifying the builder.py file in the agent's folder. For example, for the apollo agent, you can modify the builder.py file located in <mythic installation folder>/InstalledServices/apollo/apollo/mythic/agent_functions/builder.py. Restart after modification.
note for merlin: /path/to/Mythic/InstalledServices/merlin/container/payload/build/build.go

You can now also define this mapping within the wrapper (not just the agent). So in your own wrapper code (https://github.com/som3canadian/Mythic_NimSyscallPacker_Wrapper/blob/main/Payload_Type/nimsyscallpacker_wrapper/mythic/builder.py#L19) you can define `["apollo", "merlin"]` and get the same result. That way you don't have to modify each agent you want to support.

**Comment by som3canadian** [comment]
True, will fix it. We also discussed this and forgot to adapt the repo. My bad 😂

**Comment by som3canadian** [comment]
Done ✅
